In [1]:
import pandas as pd

df = pd.read_csv("../data/fakestore_raw.csv")
df.head()

,id,title,price,description,category,image,rating,price_inr,ingestion_date
0,1,"Fjallraven - Foldsack No. 1 Backpack, Fits 15 ...",109.95,Your perfect pack for everyday use and walks i...,men's clothing,https://fakestoreapi.com/img/81fPKd-2AYL._AC_S...,"{'rate': 3.9, 'count': 120}",10024.812195,2026-03-02
1,2,Mens Casual Premium Slim Fit T-Shirts,22.30,"Slim-fitting style, contrast raglan long sleev...",men's clothing,https://fakestoreapi.com/img/71-3HjGNDUL._AC_S...,"{'rate': 4.1, 'count': 259}",2033.227030,2026-03-02
2,3,Mens Cotton Jacket,55.99,great outerwear jackets for Spring/Autumn/Wint...,men's clothing,https://fakestoreapi.com/img/71li-ujtlUL._AC_U...,"{'rate': 4.7, 'count': 500}",5104.949839,2026-03-02
3,4,Mens Casual Slim Fit,15.99,The color could be slightly different between ...,men's clothing,https://fakestoreapi.com/img/71YXzeOuslL._AC_U...,"{'rate': 2.1, 'count': 430}",1457.905839,2026-03-02
4,5,John Hardy Women's Legends Naga Gold & Silver ...,695.00,"From our Legends Collection, the Naga was insp...",jewelery,https://fakestoreapi.com/img/71pWzhdJNwL._AC_U...,"{'rate': 4.6, 'count': 400}",63367.389500,2026-03-02

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              20 non-null     int64
 1   title           20 non-null     object
 2   price           20 non-null     float64
 3   description     20 non-null     object
 4   category        20 non-null     object
 5   image           20 non-null     object
 6   rating          20 non-null     object
 7   price_inr       20 non-null     float64
 8   ingestion_date  20 non-null     object
dtypes: float64(2), int64(1), object(6)
memory usage: 1.5+ KB

In [3]:
df["rating"] = df["rating"].astype(str)

df["rating_rate"] = df["rating"].str.extract(r"'rate': ([0-9.]+)").astype(float)
df["rating_count"] = df["rating"].str.extract(r"'count': (\d+)").astype(int)

df.drop(columns=["rating"], inplace=True)

In [4]:
df.isnull().sum()

id                0
title             0
price             0
description       0
category          0
image             0
price_inr         0
ingestion_date    0
rating_rate       0
rating_count      0
dtype: int64

In [6]:
df["rating_rate"].fillna(df["rating_rate"].mean(), inplace=True)
df["rating_count"].fillna(0, inplace=True)

C:\Users\solan\AppData\Local\Temp\ipykernel_8232\3432933819.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["rating_rate"].fillna(df["rating_rate"].mean(), inplace=True)
C:\Users\solan\AppData\Local\Temp\ipykernel_8232\3432933819.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["rating_count"].fillna(0, inplace=True)

In [7]:
df["category"] = df["category"].str.lower().str.strip()

In [8]:
df["category"] = df["category"].replace({
    "men's clothing": "mens clothing",
    "women's clothing": "womens clothing"
})

In [9]:
df.drop_duplicates(subset="id", inplace=True)

In [10]:
def price_band(price):
    if price < 25:
        return "Budget"
    elif price < 75:
        return "Mid"
    else:
        return "Premium"

df["price_band"] = df["price"].apply(price_band)

In [11]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              20 non-null     int64
 1   title           20 non-null     object
 2   price           20 non-null     float64
 3   description     20 non-null     object
 4   category        20 non-null     object
 5   image           20 non-null     object
 6   price_inr       20 non-null     float64
 7   ingestion_date  20 non-null     object
 8   rating_rate     20 non-null     float64
 9   rating_count    20 non-null     int64
 10  price_band      20 non-null     object
dtypes: float64(3), int64(2), object(6)
memory usage: 1.8+ KB

,id,title,price,description,category,image,price_inr,ingestion_date,rating_rate,rating_count,price_band
0,1,"Fjallraven - Foldsack No. 1 Backpack, Fits 15 ...",109.95,Your perfect pack for everyday use and walks i...,mens clothing,https://fakestoreapi.com/img/81fPKd-2AYL._AC_S...,10024.812195,2026-03-02,3.9,120,Premium
1,2,Mens Casual Premium Slim Fit T-Shirts,22.30,"Slim-fitting style, contrast raglan long sleev...",mens clothing,https://fakestoreapi.com/img/71-3HjGNDUL._AC_S...,2033.227030,2026-03-02,4.1,259,Budget
2,3,Mens Cotton Jacket,55.99,great outerwear jackets for Spring/Autumn/Wint...,mens clothing,https://fakestoreapi.com/img/71li-ujtlUL._AC_U...,5104.949839,2026-03-02,4.7,500,Mid
3,4,Mens Casual Slim Fit,15.99,The color could be slightly different between ...,mens clothing,https://fakestoreapi.com/img/71YXzeOuslL._AC_U...,1457.905839,2026-03-02,2.1,430,Budget
4,5,John Hardy Women's Legends Naga Gold & Silver ...,695.00,"From our Legends Collection, the Naga was insp...",jewelery,https://fakestoreapi.com/img/71pWzhdJNwL._AC_U...,63367.389500,2026-03-02,4.6,400,Premium

In [12]:
df.to_csv("../data/fakestore_clean.csv", index=False)
print("✅ clean dataset saved")

✅ clean dataset saved